apiVersion: v1
kind: Service
metadata:
  name: vanvyaapaar-service
spec:
  selector:
    app: vanvyaapaar
  ports:
    - name: frontend
      port: 3000
      targetPort: 3000
    - name: backend
      port: 8081
      targetPort: 8081
  type: NodePort